### PR TITLE
Minimal web

### PR DESCRIPTION
**Pull request by surenkumard**

### CODE REVIEW

**Review by niranjank2022 — COMMENTED** [review]
@surenkumard Put the images in assets or img folder.

**Comment by niranjank2022** [comment]
Also change the navbar font family!

**Comment by niranjank2022** [comment]
For the content within maintext div, "SAT PREP MADE EASY" is enough!

**Comment by niranjank2022** [comment]
And the links don't have to point to anything. Let them be, empty.

**Comment by surenkumard** [comment]
Ok niranjan

**Pull request closed without merging**
